pages/orders/urls.py
from django.urls import path
from django.urls import path
from orders.views import OrdersPageView, charge,OrdersViajePageView,OrdersHospPageView

urlpatterns=[
    path('charge/', charge, name='charge'),
    path('orders/purchase/<int:pk>',OrdersPageView.as_view(), name='orders'),
    path('orders_viaje/purchase/<int:pk>',OrdersViajePageView.as_view(), name='orders_viaje'),
    path('orders_hosp/purchase/<int:pk>',OrdersHospPageView.as_view(), name='orders_hosp'),
    
]

pages/proyecto1/urls.py
from django.urls import path,include
from django.contrib import admin
from mipagina.views import HomePageView,TecView,RegistrarView,VueloPageView,HospedajePageView,DescripViajesPageView,DescripVuelosPageView,DescripHospPageView,ViajeDeleteView,AboutPageView
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from orders.views import OrdersPageView, charge
#rutas para los templates 
urlpatterns = [
    path('admin/', admin.site.urls),
     path('accounts/', include('allauth.urls')),
    path('mipagina/', include('mipagina.urls')),
    path('orders/', include('orders.urls')),
    path('charge/', charge, name='charge'),
    path('orders/purchase',OrdersPageView.as_view(), name='orders'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('Home',HomePageView.as_view(), name='home'),
    path('', TemplateView.as_view(template_name='vuelo.html'), name='vuelo'),
    path('vuelo',VueloPageView.as_view(), name='vuelo'),
    path('', TemplateView.as_view(template_name='hospedaje.html'), name='hospedaje'),
    path('hospedaje',HospedajePageView.as_view(), name='hospedaje'),
    path('Acerca_de', TemplateView.as_view(template_name='About.html'), name='About'),
    path('Acerca_de',AboutPageView.as_view(), name='About'),
    path('Tec',TecView.as_view(), name='tec'),
    path('registrar/', RegistrarView.as_view(),name='registrar'),
    path('Descripcion/Viajes/<int:pk>',DescripViajesPageView.as_view(),name='DescViajes'),
    path('Descripcion/Vuelos/<int:pk>',DescripVuelosPageView.as_view(),name='DescVuelos'),
    path('Descripcion/Hospedajes/<int:pk>',DescripHospPageView.as_view(),name='DescHosp'),
    path('Viaje/<int:pk>/delete',ViajeDeleteView.as_view(),name='deleteViaje'),
    path('oauth/', include('social_django.urls', namespace='social')), 
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/mipagina/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model



# Create your models here.

#modelo del usario personalizado del proyecto final
class UsuarioPers(AbstractUser):
    edad = models.PositiveIntegerField(null=True, blank=True)
    telefono = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    genero = models.CharField(null=True,blank=True, max_length=1)
    
    

#se presntan los diferentes modelos de la base de datos diseñada en posgres 
#modelo de las ciudades 
class Ciudad(models.Model):
    nombre = models.TextField(default="")
    
    def __str__(self):
        return self.nombre

#modelo de hospedaje en la base de datos 
class Hospedaje(models.Model):
    ciudad = models.TextField(default="")
    beneficios = models.TextField(default="")
    presio = models.TextField(default="")
    img =models.ImageField(null=True, blank=True, upload_to="images/")
  
    class Meta:
        permissions = [
            ('add_access','Permite agregar registros'),
        ]

    def __str__(self):
        return self.ciudad

    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])

#modelo de vuelo en la base de datos 
class Vuelo(models.Model):
    ciudad = models.TextField(default="")
    descrpicion = models.TextField(default="")
    escala = models.TextField(default="")
    presio = models.TextField(default="")
    img = models.ImageField(null=True, blank=True, upload_to="images/")
    
    class Meta:
        permissions = [
            ('usuariocomun','Permite a los usarios agregar,editar,eliminar'),
        ]
    
    def __str__(self):
        return self.ciudad

    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])

#modelo de viaje en la base de datos 
class Viaje(models.Model):
    ciudad = models.TextField(default="")
    descrpicion = models.TextField(default="")
    presio = models.TextField(default="")
    img = models.ImageField(null=True, blank=True, upload_to="images/")
    noches = models.TextField(default="")

    class Meta:
            permissions = [
                ('usuarioPerTot','Permite a los usarios agregar,editar,eliminar en modelo viaje'),
            ]
    def __str__(self):
        return self.ciudad

    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])


#modelo de los comentarios  agregando dos llaves foraneas para los autores y los usarios
class ComentarioVuelo(models.Model):
    comentario = models.TextField(default="")
    Vuelo = models.ForeignKey(
        Vuelo,
        default="",
        on_delete= models.CASCADE,
    )
        
    def __str__(self):
        return self.comentario
    
class ComentarioViaje(models.Model):
    comentario = models.TextField(default="")
    Viaje = models.ForeignKey(
        Viaje,
        default="",
        on_delete= models.CASCADE,
    )
        
    def __str__(self):
        return self.comentario
    

class ComentarioHosp(models.Model):
    comentario = models.TextField(default="")
    Hospedaje = models.ForeignKey(
        Hospedaje,
        default="",
        on_delete= models.CASCADE,
    )
    

    def __str__(self):
        return self.comentario
    

pages/templates/About.html
<style>
    #contabout{
        width: 1350px;
        height: 600px;
        background-color: brown;
        padding-top: 50px;
    }
    #contabout1{
        width: 550px;
        height: 500px;
        background-color: #ffffff;
        margin-left: 400px;

         border-style: solid;
        border-color: rgba(14, 13, 13, 0.219);
        border-radius: 5px;   
    }
    #up_tit{
        text-align: center;
        border-bottom-color:rgba(14, 13, 13, 0.219);
        border-bottom-style: solid;

    }
    #btn_azul{
        background-color: blue;
        color: white;
        width: 200px;
        margin-left: 150px;
       
    }
</style>
<!--Agregar el archivo base -->
{% extends 'base.html' %}
{% block content %}
<!--creacion del archivo de acerca de de la empresa que contendra la informacion de la empresa ademas de
un boton que te direccionara a la pagina del tecnologico  -->
   <div id="contabout">
        <div id="contabout1">
            <div id="up_tit"><h3>Acerca de Go Travel</h3></div>
            <div style="height: 60%;">
                <h3 style="text-align: center;">Mision</h3>
                <p style="text-align: center;">nuestra mision es ser la mejor empresa de transporte del pais ademas de ser una de las empresas mas grandes que exista </p>

                <h3 style="text-align: center;">Vision</h3>
                <p style="text-align: center;">ser una de las 5 empresas principales de viaje en el mundo otorgando el ejor serviso a nuestros clientes</p>
                
               
            </div>

            <div>
                <p style="text-align: center;">derechos reservados. crador y director del proyecto Ivan Andres Puentes Cortez proyecto de la unidad 3 de la materia de pila 2 </p>
                <a type="button" id="btn_azul" class="btn"  href="{%url 'tec'%}">Tecnologico</a>

            </div>
        </div> 
   </div>

{% endblock content %}

pages/templates/CreateViaje.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_descrpicion{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_noches{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>

{% extends 'base.html' %}
{% block content %}
<!--creacion de un nuevo viaje -->

<div id="conte_vuelo">
<h1 id="tit">Agregar Viajes</h1>
<form action="" method="post"  enctype="multipart/form-data">
    {% csrf_token %} 
    {{form.media}}
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>



<!--fin de la declaracion del carusel -->
{% endblock content %}

pages/templates/CreateVuelo.html
<style>
   p{
        color: white;
    }
    #id_ciudad{
        width: 350px;
        height: 30px;
        margin-left: 35px;
    }
    #id_descrpicion{
        width: 350px;
        height: 30px;
        margin-left: 10px;
    }
    #id_escala{
        width: 350px;
        height: 30px;
        margin-left: 40px;
    }
    #id_presio{
        width: 350px;
        height: 30px;
        margin-left: 45px;
    }
    #id_img{
        width: 350px;
        height: 30px;
        margin-left: 50px;
    }
    #btn_guardar{
        color:green;
        width: 150px;
        height: 40px;
    }
    #tit{
        color: white;
        font-family: Arial, Helvetica, sans-serif;
        margin-bottom: 30px;
    }
    #conte_vuelo{
        text-align: center;
    }

</style>
{% extends 'base.html' %}
{% block content %}
<!--creacion de un nuevo vuelo -->
<div id="conte_vuelo">
    <h1 id="tit"> Agregar Vuelo</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{form.media}}
        {{form.as_p}}
    <input type="submit" value="Guardar" id="btn_guardar"> 
    </form>
</div>



{% endblock content %}

pages/templates/DescHosp.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_beneficios{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_escala{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>

{% extends 'base.html' %}
{% load static %}
<!--descripcion de un Hospedaje   -->
<ul id="lista_1">
    <h1> Descripcion del viaje</h1>
    
    {% block content %}
    
         <!--descripcion de un modelo de hospedaje   -->
   
    <div id="datos_div">
        <img id="img_div" src = {{Listado_viajes_des.img.url}} >
        <div>Destino:{{Listado_viajes_des.ciudad}}</div>
        <div>Detalles:{{Listado_viajes_des.descrpicion}}</div>
        <div>Numero de Noches:{{Listado_viajes_des.noches}}</div>
        <a type="button" class="btn" href="{% url 'orders_hosp' Listado_viajes_des.pk %}" id="btn_comprar"><strong>Pagar: ${{Listado_viajes_des.presio}}</strong></a>
        
    </div>

    
    {% endblock content %}
</ul>  

pages/templates/DescViajes.html
<style>
#img_div
{
    width: 50%;
    height: 70%;
}
#datos_div{
    margin-left: 200px;
    padding-top: 20px;
    text-align: center;
    background-color: white;
    width: 800px;
    height: 500px;
    border-color: rgba(192, 3, 3, 0.24);
    background-color: rgba(13, 108, 216, 0.568);
    border-radius: 10px;
    border-style: solid;
}
#btn_comprar{
    background-color: rgb(255, 255, 255);
    border-color: rgba(128, 128, 128, 0.226);
    color: indigo;
    border-radius:10px;
}

</style>

{% extends 'base.html' %}
{% load static %}
<!--descripcion de un viaje   -->
<ul id="lista_1">
    <h1> Descripcion del viaje</h1>
    
    {% block content %}
    

    <div id="datos_div">
        <img id="img_div" src = {{Listado_viajes_des.img.url}} >
        <div>Destino:{{Listado_viajes_des.ciudad}}</div>
        <div>Detalles:{{Listado_viajes_des.descrpicion}}</div>
        <div>Numero de Noches:{{Listado_viajes_des.noches}}</div>
        <a type="button" class="btn" href="{% url 'orders_viaje' Listado_viajes_des.pk %}" id="btn_comprar"><strong>Pagar: ${{Listado_viajes_des.presio}}</strong></a>
         
        
    </div>

    
    {% endblock content %}
</ul>  

pages/templates/EditarHospedaje.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_beneficios{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_escala{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>
 {% extends 'base.html' %}
<!--valores para ediar del modelo de Hospedaje-->
{% block content %}

<div id="conte_vuelo">
    <h1 id="tit">Editar Hospedaje</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{form.media}}
        {{form.as_p}}
      <input type="submit" id="btnjs" value="Guardar" id="btn_guardar"> 
    </form>

    
   

</div>


{%endblock content %}

pages/templates/EditarViaje.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_descrpicion{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_noches{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>
{% extends 'base.html' %}


<!--valores para ediar del modelo de Viajes-->
{% block content %}

<div id="conte_vuelo">
    <h1 id="tit">Editar Viajes</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}} 
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>
</div
{%endblock content %}

pages/templates/EditarVuelo.html
<style>
    p{
         color: white;
     }
     #id_ciudad{
         width: 350px;
         height: 30px;
         margin-left: 35px;
     }
     #id_descrpicion{
         width: 350px;
         height: 30px;
         margin-left: 10px;
     }
     #id_escala{
         width: 350px;
         height: 30px;
         margin-left: 40px;
     }
     #id_presio{
         width: 350px;
         height: 30px;
         margin-left: 45px;
     }
     #id_img{
         width: 350px;
         height: 30px;
         margin-left: 50px;
     }
     #btn_guardar{
         color:green;
         width: 150px;
         height: 40px;
     }
     #tit{
         color: white;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 30px;
     }
     #conte_vuelo{
         text-align: center;
     }
 
 </style>
{% extends 'base.html' %}
<!--valores para ediar del modelo de Vuelo-->
{% block content %}

<div id="conte_vuelo">
    <h1 id="tit">Editar Vuelos</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{form.media}}
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>
</div>
{%endblock content %}

pages/templates/Tec.html
{% extends 'base.html' %}
{% load static %}
<!--creacion de una platilla del tecnologico donde se puede visualizar algo de la historia y de los  -->
{% block content %}
      <div class="contenido" id="contenido">
        <img class="d-block w-100" src="{% static 'img/4.jpg' %}">
        <h1 id="h1_t">Conoce mas ....</h1>
        <button id="btnjs" style="margin-left: 600px;" class="btn btn-primary">Ver Detalles</button>
      </div>

      <div id="modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Tecnologico de la laguna </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
             <h6>Historia</h6>
                <p>
                El Instituto Tecnológico Regional de La Laguna No. 13, llamado así en un principio[cita requerida], se creó con el fin de satisfacer la necesidad de contar con técnicos especializados y profesionistas capaces de promover, planear, dirigir y organizar las industrias existentes y las de nueva creación.

                Se creó por la iniciativa de un grupo de egresados del Instituto Politécnico Nacional y a la acción conjunta del entonces Presidente de la República, el Lic. Gustavo Díaz Ordaz y el Alcalde de Torreón, el Ing. Heriberto Ramos González.[cita requerida]
                
                Hasta el año de 1987, se contaba con la impartición de educación de nivel medio superior</p>
                <h6>Eventos</h6>
                <img class="d-block w-100" src="{% static 'img/25.png' %}" alt="Second slide">
            </div>
            <div class="modal-footer">
              
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
	
	  <!--uso de java script para la visualizacion de un modal-->
<script>
$(document).ready(function(){
    $("#btnjs").click(function(){
        $('#modal').modal('show');      
})
})
</script>


{% endblock content%}

pages/templates/comentarioNuevo.html
{% extends 'base.html' %}

{% block content %}
<h1> Comentarios</h1>
<form action="" method="post">{% csrf_token %} 
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>
{%endblock content %}

pages/templates/comentarioNuevoV.html
{% extends 'base.html' %}

{% block content %}
<h1> Comentarios</h1>
<form action="" method="post">{% csrf_token %} 
    {{form.as_p}}
<input type="submit" value="Guardar" id="btn_guardar"> 
</form>
{%endblock content %}

pages/templates/deleteVuelos.html
<style>
    #tit{
       color: white;
       font-family: Arial, Helvetica, sans-serif;
       margin-bottom: 30px;
   }

   #btn_guardar{
       color:red;
       width: 150px;
       height: 40px;
       margin-left: 600px;
   }
</style>
{% extends 'base.html' %}
{% block content %}

<!--Formulario para eliminar-->

<h1 id="tit">Seguro que deseas eliminar este registro?</h1>
<form action="" method="post">{% csrf_token %} 
  {{form.as_p}}
<input type="submit" value="Confirmar" id="btn_guardar"> 
</form>
{%endblock content %}

pages/templates/home.html
<style>
	.carousel-inner img{
			width: 100px;
			height: 500px;
		}

		#carouselExampleIndicators{
			width: 1370px;
		
		}
		#btn_verde{
		
			color: white; 
			border-color: green;
			width: 200px;
			margin: 10px 0px 0px 570px;
			
		}
		#btn_azul{
			color: white; 
			border-color: blue;
			width: 200px;
			margin: 10px 0px 0px 120px;
		}

		#btn_rojo{
			color: white; 
			border-color: red;
			width: 200px;
			margin: 10px 0px 0px 120px;
		}
		#btn_rojo_1{
			color: rgb(103, 31, 117); 
			border-color: rgba(65, 65, 65, 0.781);
			background-color: white;
			width: 200px;
			margin: 10px 0px 0px 120px;
		

		}

		#titulos_h4_su{
		
			color: white; 
			font-family: Arial, Helvetica, sans-serif;
			text-align: center;
		}
		#viajes_cont{
			width: 33%;
			float: left;
			margin-top: 50px;
			margin-bottom: 150px;
		}

		#viajes_cont_1{
			width: 32%;
			float: left;
			margin-top: 50px;
			padding-top: 50px;
			margin-bottom: 50px;
			border-style: solid;
			border-color: rgba(65, 65, 65, 0.356);
			margin-left: 5px;
			height: 500px;
			border-radius: 15px;
			background-color: white;
			
		}

		#li_titulo_bd{
			list-style: none;
			color: black;
			text-align: center;
			font-family: Arial, Helvetica, sans-serif;
			font-size: 20px;
		}
		#li_titulo_bd_1{
			list-style: none;
			color: white;
			text-align: center;
			font-family: Arial, Helvetica, sans-serif;
			font-size: 20px;
		}
		#home_img{
			width: 65%;
			height: 50%;
			margin-left: 65px;
		}

</style>
<!--en este modelo se puede apreciar como esta dividio en usario super usario un usario sin registrar-->
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_superuser%}
<!--el super usario tiene mayor privilegios como son los de editar agregar o eliminar viajes -->
<div>
	
	<div>
			
		<h4 id="titulos_h4_su">Registro de Viajes</h4>
		<div>
		  <a type="button" id="btn_verde" class="btn" href="{% url 'CreateViaje' %}">Agreagar</a>
		</div>

		<div >
			{%for post in Listado %}
				<div id="viajes_cont">

						<img id="home_img" src = {{post.img.url}} >
						<li id="li_titulo_bd_1">Destino: {{ post.ciudad }}</li>
						<li id="li_titulo_bd_1">Descrpicion: {{ post.descrpicion }}</li>
						<li id="li_titulo_bd_1">Presio:$ {{ post.presio }}</li>
						<li id="li_titulo_bd_1">Numero de Noches:{{ post.noches }}</li>
						<div>
							<a type="button" id="btn_azul" class="btn"  href="{%url 'EditarViaje' post.pk %}">Editar</a>
						</div>
						<div>
							<a type="button" id="btn_rojo" class="btn"  href="{%url 'deleteViaje' post.pk %}">Eliminar</a>
						</div>
				</div>
		
			{% endfor %}

			
		</div>
	</div>
	


  </div>


{% elif user.is_authenticated%}
<!--el usario tiene mayor privilegios como el de poder comprar los boletos -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
	  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
	  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
	  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
		<div class="carousel-item active">
		  <img class="d-block w-100" src="{% static 'img/fondo.jpg' %}">
		</div>
		<div class="carousel-item">
		  <img class="d-block w-100" src="{% static 'img/fondo2.jpg' %}" alt="Second slide">
		</div>
		<div class="carousel-item">
		  <img class="d-block w-100" src="{% static 'img/fondo3.jpg' %}" alt="Third slide">
		</div>
	  </div>
	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	  <span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	  <span class="carousel-control-next-icon" aria-hidden="true"></span>
	  <span class="sr-only">Next</span>
	</a>
  </div>

		{%for post in Listado %}
		<div id="viajes_cont_1">

				<img id="home_img" src = {{post.img.url}} >
				<li id="li_titulo_bd"><strong>Destino: {{ post.ciudad }}</strong></li>
				<li id="li_titulo_bd">Descrpicion: {{ post.descrpicion }}</li>
				<li id="li_titulo_bd">Presio:$ {{ post.presio }}</li>
				<li id="li_titulo_bd">Numero de Noches:{{ post.noches }}</li>
			
				<div>
					<a type="button" id="btn_rojo_1" class="btn"  href="{% url 'DescViajes' post.pk %}"><strong>Ver mas...</strong></a>
				</div>
				<a type="button" class="btn" href="{% url 'comentarioNuevoV' post.pk %}" id="btn_rojo_1"><strong>Comentar</strong></a>
				{%for Comentarios in Listado1 %}
						<samp class="font-wigth-bold">{{ Comentarios.comentarios}}</samp>	
				{%endfor%}

				
		</div>

		{% endfor %}
{% else %}
<!--y el usario sin rol solo puede ver -->

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
	  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
	  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
	  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
	  <div class="carousel-item active">
		<img class="d-block w-100" src="{% static 'img/fondo.jpg' %}">
	  </div>
	  <div class="carousel-item">
		<img class="d-block w-100" src="{% static 'img/fondo2.jpg' %}" alt="Second slide">
	  </div>
	  <div class="carousel-item">
		<img class="d-block w-100" src="{% static 'img/fondo3.jpg' %}" alt="Third slide">
	  </div>
	</div>
	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	  <span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	  <span class="carousel-control-next-icon" aria-hidden="true"></span>
	  <span class="sr-only">Next</span>
	</a>
  </div>

		{%for post in Listado %}
		<div id="viajes_cont_1">

				<img id="home_img" src = {{post.img.url}} >
				<li id="li_titulo_bd"><strong>Destino: {{ post.ciudad }}</strong></li>
				<li id="li_titulo_bd">Descrpicion: {{ post.descrpicion }}</li>
				<li id="li_titulo_bd">Presio:$ {{ post.presio }}</li>
				<li id="li_titulo_bd">Numero de Noches:{{ post.noches }}</li>
				<div>
					<a type="button" id="btn_rojo_1" class="btn"  href="{% url 'DescViajes' post.pk %}"><strong>Comprar</strong></a>
				</div>
		</div>

		{% endfor %}

  {% endif %}


<!--fin de la declaracion del carusel -->
{% endblock content %}
		









  